//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automerge_nevlabs.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automerge_nevlabs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh1 {
            get {
                object obj = ResourceManager.GetObject("Refresh1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;XCoolForm&gt;
        ///   &lt;XCoolFormElements&gt;
        ///      &lt;TitleBar&gt;
        ///	&lt;InnerBorderColor r=&quot;212&quot; g=&quot;208&quot; b=&quot;200&quot;&gt;&lt;/InnerBorderColor&gt;
        ///	&lt;OuterBorderColor r=&quot;200&quot; g=&quot;200&quot; b=&quot;200&quot;&gt;&lt;/OuterBorderColor&gt;
        ///        &lt;TitleBarCaptionColor r=&quot;255&quot; g=&quot;255&quot; b=&quot;255&quot;&gt; &lt;/TitleBarCaptionColor&gt;
        ///	&lt;ButtonBox&gt;    
        ///            &lt;MixColor1 r=&quot;255&quot; g=&quot;255&quot; b=&quot;255&quot;&gt; &lt;/MixColor1&gt;
        ///	    &lt;MixColor2 r=&quot;212&quot; g=&quot;208&quot; b=&quot;200&quot;&gt; &lt;/MixColor2&gt;
        ///	    &lt;MixColor3 r=&quot;212&quot; g=&quot;208&quot; b=&quot;200&quot;&gt; &lt;/MixColor3&gt;
        ///	    &lt;MixColor4 r=&quot;212&quot; g=&quot;208&quot; b=&quot;200&quot;&gt; &lt;/MixColor4&gt;
        ///	    [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string StandardWindowsTheme {
            get {
                return ResourceManager.GetString("StandardWindowsTheme", resourceCulture);
            }
        }
    }
}
